### ISSUE TITLE
Page configuration "pages" not working

### ISSUE THREAD

**Issue by pgmgb** [rundeck-plugins/ui-plugin-examples#3]
We created a custom Rundeck UI plugin, which is working as expected, when we're use the following plugin metadata:
```yml
---
name: custom-output-ui
version: 0.1
rundeckPluginVersion: 2.0
targetHostCompatibility: unix
rundeckCompatibilityVersion: 4.x
providers:
  - service: UI
    name: custom-output-ui
    plugin-type: ui
    title: "custom output UI"
    description: "Adds Rundeck job execution output to UI."
    ui:
      - pages: "*"
        scripts:
          - js/custom-output-ui.js
```

At the moment, the plugin is loaded for each page (-> `pages: "*"`). The goal would be to load the plugin only for pages like `/project/*/execution/show/*`. As seen in [UI Plugin Provider Declaration](https://docs.rundeck.com/docs/developer/11-ui-plugins.html#zip-plugin-type), we modified the plugin metadata as shown below. After the modification, the plugin will not be loaded anymore.
```yml
    ui:
      - pages: "/project/*/execution/show/*"
        scripts:
          - js/custom-output-ui.js
```

Is it possible to restrict the loading of the plugin only to the path `/project/*/execution/show/*`?
And if yes, how?

Our Rundeck version: 4.15.0
